### ISSUE TITLE
webapp pod

### ISSUE THREAD

**Issue by mpouyakh7** [DickChesterwood/k8s-fleetman#37] opened 2020-05-04 10:21 UTC
When I deployed the fleetman-webapp pod to my cluster, it gives Back-off starting error.

and I logged the pod, the message is : 

host not found in upstream "fleetman-api-gateway.default.svc.cluster.local" in /etc/nginx/nginx.conf:23
nginx: [emerg] host not found in upstream "fleetman-api-gateway.default.svc.cluster.local" in /etc/nginx/nginx.conf:23

Would you please help me in solving this issue?

**Comment by RichardKnowles** [comment] 2020-05-04 14:53
This will be due to a fault with the fleetman-api-gateway service. You need to have a service defined for that and backed up with a healthy pod. Have you deployed the services.yaml file yet?

**Comment by mpouyakh7** [comment] 2020-05-04 15:12
> gateway

yes I deployed all the service.
This is the same as the course.
=============================================
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
  
spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: api-gateway

  ports:
    - name: http
      port: 8080
      nodePort: 30020

  type: NodePort

**Comment by RichardKnowles** [comment] 2020-05-05 14:33
Diagnostics: paste up the output from

kubectl get svc
kubectl describe svc fleetman-api-gateway
kubectl get po --show-labels
kubectl logs <name of api gatway pod>

Enclose the output in three backticks to use monospace font.

```
Like this
```

**Comment by mpouyakh7** [comment] 2020-05-08 13:38
> Diagnostics: paste up the output from
> 
> kubectl get svc
> kubectl describe svc fleetman-api-gateway
> kubectl get po --show-labels
> kubectl logs
> 
> Enclose the output in three backticks to use monospace font.
> 
> ```
> Like this
> ```

Hi,
Actually I solved the issue by deploying in default namespaces.
but I don't know why it doesn't show the vehicles on the left menu and it is empty.
It appeared once but after that I tried so much but it didn't show the vehicles.

**Comment by RichardKnowles** [comment] 2020-05-08 15:36
Ah sorry about that - yes we (stupidly) hardcoded the "default" namespace into the DNS name.
But you should be seeing vehicles.
#1 cause for this is a lack of resources. Did you run minikube with 4Gb of memory? If not, then restart with:
minikube delete # important 
minikube start --memory 4096
If it's not that then the diagnostics above will be useful. Although this time all we need is:
kubectl get all

**Comment by mpouyakh7** [comment] 2020-05-09 15:24
> Ah sorry about that - yes we (stupidly) hardcoded the "default" namespace into the DNS name.
> But you should be seeing vehicles.
> #1 cause for this is a lack of resources. Did you run minikube with 4Gb of memory? If not, then restart with:
> minikube delete # important
> minikube start --memory 4096
> If it's not that then the diagnostics above will be useful. Although this time all we need is:
> kubectl get all

thank you for your help, my issue solved.

**Comment by traintes** [comment] 2020-05-23 09:31
I'm getting the same error and just increasing the memory for minikube did not resolve it for me. I can reproduce the error on my machine even when using the files provided in this repository.

Here's what I did:

```
$ minikube stop
$ minikube delete
$ minikube start --memory 4096
$ git clone https://github.com/DickChesterwood/k8s-fleetman.git
$ cd k8s-fleetman/_course_files/Chapter\ 11\ Microservices/
$ kubectl apply -f .

// Waiting here until everything is loaded and the webapp pod starts to fail (verify using kubectl get all)

$ kubectl get svc
NAME                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                          AGE
fleetman-api-gateway        NodePort    10.111.45.17     <none>        8080:30020/TCP                   5m10s
fleetman-position-tracker   ClusterIP   10.102.190.11    <none>        8080/TCP                         5m10s
fleetman-queue              NodePort    10.107.242.146   <none>        8161:30010/TCP,61616:30749/TCP   5m10s
fleetman-webapp             NodePort    10.103.82.89     <none>        80:30080/TCP                     5m10s
kubernetes                  ClusterIP   10.96.0.1        <none>        443/TCP                          5m39s

$ kubectl describe svc fleetman-api-gateway
Name:                     fleetman-api-gateway
Namespace:                default
Labels:                   <none>
Annotations:              Selector:  app=api-gateway
Type:                     NodePort
IP:                       10.111.45.17
Port:                     http  8080/TCP
TargetPort:               8080/TCP
NodePort:                 http  30020/TCP
Endpoints:                172.18.0.6:8080
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>

$ kubectl get po --show-labels
NAME                                 READY   STATUS    RESTARTS   AGE     LABELS
api-gateway-7d5db748dc-hz7tq         1/1     Running   0          5m42s   app=api-gateway,pod-template-hash=7d5db748dc
position-simulator-f48b877cb-5jgw6   1/1     Running   0          5m42s   app=position-simulator,pod-template-hash=f48b877cb
position-tracker-f598c64d6-v5v6b     1/1     Running   0          5m42s   app=position-tracker,pod-template-hash=f598c64d6
queue-56b7dbb465-6xskz               1/1     Running   0          5m42s   app=queue,pod-template-hash=56b7dbb465
webapp-7786d4d77d-cvc2p              0/1     Error     3          5m42s   app=webapp,pod-template-hash=7786d4d77d

$ kubectl logs webapp-7786d4d77d-cvc2p 
2020/05/23 09:11:04 [emerg] 1#1: host not found in upstream "fleetman-api-gateway.default.svc.cluster.local" in /etc/nginx/nginx.conf:23
nginx: [emerg] host not found in upstream "fleetman-api-gateway.default.svc.cluster.local" in /etc/nginx/nginx.conf:23

$ minikube version
minikube version: v1.10.1
commit: 63ab801ac27e5742ae442ce36dff7877dcccb278

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Could you please help me resolve this issue?

**Comment by DickChesterwood** [comment] 2020-05-23 11:46
This is because the service discovery of fleetman-api-gateway.blah.blah is failing. 

Assuming there's no problems with the yaml - and there shouldn't be as you've done a direct clone, the only thing I can think of here is that the DNS service in your minikube is failing.

I've just answered a Q&A on Udemy very similar to this - are you the same person running on RHEL?

If not, then to confirm whether it's DNS:

exec into a pod. The api-gateway pod definitely has nslookup available, so use that one:

kubectl exec -it <api gateway pod name> sh

Next try a DNS lookup:

`/usr/local/bin # nslookup fleetman-queue
`
You should get output like the following:

```
nslookup: can't resolve '(null)': Name does not resolve

Name:      fleetman-queue
Address 1: 10.101.127.114 fleetman-queue.default.svc.cluster.local
```

This is showing the other pod could be found with an IP address.

I suspect - I'm hoping in fact - that this will fail for you, indicating there's something wrong with your minikube.

If that's the case, what's your OS etc?

**Comment by traintes** [comment] 2020-05-23 12:33
No, I'm not the same person as that one from Udemy. The output does not show any errors when I issue the DNS lookup command from within the api-gateway pod. It is the same as yours (apart from the different IP address, obviously):

```
$ kubectl exec -it api-gateway-7d5db748dc-sg2gg sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
/usr/local/bin # nslookup fleetman-queue
nslookup: can't resolve '(null)': Name does not resolve

Name:      fleetman-queue
Address 1: 10.103.158.146 fleetman-queue.default.svc.cluster.local
```

And just to be sure: I have cleared and restarted minikube in the meantime. Therefore the output of the command (the IP address of the service) does not match the outputs of the previous post.

I'm running on an Ubuntu 18.04.4 machine using pretty recent versions of minikube and kubectl as I've installed it on Wednesday. I've already added the exact version numbers in the end of the last post.

**Comment by DickChesterwood** [comment] 2020-05-24 14:29
Now this is interesting, because coincidentally the udemy person has exactly the same symptons, and they too are getting perfect correct results back from DNS. The only difference is they're running on RHEL 8, but this leads me to think it might be something that is affecting native linux installations.

I'm not sure what, but the next thing to ask is how are you running minikube? Are you using a driver?

As I understand it (sorry, at present due to lockdown I don't have access to a proper linux machine, just this weird windows based gaming rig - flashing but unreliable), minikube won't run properly if you use one of the vm-drivers like virtualbox. 

minikube delete
minikube start --memory 4096 --driver none

This should use the native docker rather than one buried a virtual machine.

Sorry if you're already doing this, but it's definitely the next thing to check off before looking deeper (although I'll stuggle if it isn't this).

Also sorry that it's taking a day for each question/response cycle, I'm sweeping support calls up once a day before recording. So it might take a while!

**Comment by traintes** [comment] 2020-05-24 19:42
Never mind the response cycle. I understand that resolving this might take a few tries as it seems like the problem is a consequence of some specific circumstances.

Up until now I've never specified the driver option when starting minikube. The output on the terminal states that it is then defaulting to the docker driver.

So I tried starting minikube with the none driver using the command from above. However, the result is still the same - the webapp pod is constantly crashing and restarting with the same error.

And just for reference and reproducability: I had to clear a few hurdles along the way before starting minikube with the none driver actually worked. Here's what I did:
- Using the none driver the `minikube start` command has to be run as root user (so I prefixed it with sudo).
- A warning states that the none driver ignores the `--memory` flag (so I dropped it from the command).
- I had to install an additional package first (`sudo apt install conntrack -y`).
- After starting minikube a few messages appeared about configurations. I'm not repeating them here, because they were in German (which is the system language of my OS). I resolved that by setting an environment variable as described (`export CHANGE_MINIKUBE_NONE_USER=true`).
- All following kubectl commands (`kubectl apply`, `kubectl get`, etc.) had to be issued as root (so I prefixed them with sudo).

**Comment by DickChesterwood** [comment] 2020-05-25 14:59
Thanks for the info. I might have a lead. I was reading the doc here:

https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

This was out of desperation really, because DNS seems to be working just fine.

But, there's one line near the bottom under "known issues":

"If you are using Alpine version 3.3 or earlier as your base image, DNS may not work properly due to a known issue with Alpine. Check here for more information."

Now, I am using nginx:1.14.0-alpine for the webapp container. I can't tell easily which version of alpine that is built upon, BUT it's a good bet that it might be earlier than 3.3.

I need to try rebuilding that image, I'll get rid of the alpine and push an image for you to try. I have to leave the office now for a short while but I'll get on this as soon as I am back...

**Comment by DickChesterwood** [comment] 2020-05-25 20:36
Right, I've built a testing image of the webapp based on regular nginx image and not the alpine version.

Can you try switching the image for the webapp to be:

richardchesterwood/k8s-fleetman-webapp-angular:testing-version-8

Reapply the yaml and you will need to do a hard refresh on your browser (I forgot this was necessary and was tearing my hair out making many changes with no effect!)

It should say "Fleet Management System R2 Testing"

This is a bit of a long shot, but you never know.

**Comment by traintes** [comment] 2020-05-26 07:46
I've tested it now. Using this testing image the webapp pod is working and doesn't crash anymore (it also says "Fleet Management System R2 Testing"). It really looks like this has been the problem all the way...

However, no "live" truck data is being displayed on the map. I assume that this is just a consequence of using the testing image and that the image doesn't have everything implemented now. Is that correct?

**Comment by DickChesterwood** [comment] 2020-05-26 14:45
Wow. 

This is huge. It's probably affected many customers over the past two years - assuming this only affects bare metal linux users (I'm unclear about that), maybe there aren't so many of those.

But - you should definitely be seeing vehicles, it was working for me here although I did have a lot of frustrating niggles getting my version running (hence version-8). 

Of course, the other containers also rely on DNS lookups (although, for them, startup doesn't rely on this, so they will run fine but might be spitting out errors). Can you show me the logs from the position tracker pod? I'm expecting lots of errors there if it can't connect to the queue.

If that's the case, I need to build fresh images for the entire system. This is going to be a nasty fix indeed!

**Comment by traintes** [comment] 2020-05-30 13:15
Sorry for the delayed reply regarding your last message. For some reason the GitHub notifications started being moved into the spam folder of my e-mail inbox and so I didn't get any notifications about them.

Considering the log output of the position-tracker pod below it does look like this. There are lots of connection errors.

```
$ kubectl logs -f position-tracker-f598c64d6-vq96x 

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.4.0.RELEASE)

2020-05-30 13:02:36.801  INFO 1 --- [           main] c.v.tracker.PositionTrackerApplication   : Starting PositionTrackerApplication v0.0.1-SNAPSHOT on position-tracker-f598c64d6-vq96x with PID 1 (/webapp.jar started by root in /)
2020-05-30 13:02:36.812  INFO 1 --- [           main] c.v.tracker.PositionTrackerApplication   : The following profiles are active: production-microservice
2020-05-30 13:02:37.176  INFO 1 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@108c4c35: startup date [Sat May 30 13:02:37 UTC 2020]; root of context hierarchy
2020-05-30 13:02:43.281  INFO 1 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2020-05-30 13:02:43.306  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service Tomcat
2020-05-30 13:02:43.308  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.4
2020-05-30 13:02:43.576  INFO 1 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-05-30 13:02:43.576  INFO 1 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 6404 ms
2020-05-30 13:02:44.300  INFO 1 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
2020-05-30 13:02:44.307  INFO 1 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2020-05-30 13:02:44.307  INFO 1 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2020-05-30 13:02:44.308  INFO 1 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2020-05-30 13:02:44.308  INFO 1 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2020-05-30 13:02:45.475  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@108c4c35: startup date [Sat May 30 13:02:37 UTC 2020]; root of context hierarchy
2020-05-30 13:02:45.679  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/vehicles/],methods=[GET]}" onto public java.util.Collection<com.virtualpairprogrammers.tracker.domain.VehiclePosition> com.virtualpairprogrammers.tracker.rest.PositionReportsController.getUpdatedPositions(java.util.Date)
2020-05-30 13:02:45.681  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/vehicles/{vehicleName}],methods=[GET]}" onto public org.springframework.http.ResponseEntity<com.virtualpairprogrammers.tracker.domain.VehiclePosition> com.virtualpairprogrammers.tracker.rest.PositionReportsController.getLatestReportForVehicle(java.lang.String)
2020-05-30 13:02:45.685  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2020-05-30 13:02:45.685  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2020-05-30 13:02:45.800  INFO 1 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2020-05-30 13:02:45.803  INFO 1 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2020-05-30 13:02:45.923  INFO 1 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2020-05-30 13:02:46.875  INFO 1 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2020-05-30 13:02:46.925  INFO 1 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 2147483647
2020-05-30 13:02:54.320  INFO 1 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
2020-05-30 13:02:54.327  INFO 1 --- [           main] c.v.tracker.PositionTrackerApplication   : Started PositionTrackerApplication in 18.747 seconds (JVM running for 19.692)
2020-05-30 13:02:59.255  INFO 1 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : JMS message listener invoker needs to establish shared Connection
2020-05-30 13:03:00.284 ERROR 1 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'positionQueue' - retrying using FixedBackOff{interval=5000, currentAttempts=0, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://fleetman-queue.default.svc.cluster.local:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
2020-05-30 13:03:06.304 ERROR 1 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'positionQueue' - retrying using FixedBackOff{interval=5000, currentAttempts=1, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://fleetman-queue.default.svc.cluster.local:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
2020-05-30 13:03:12.316 ERROR 1 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'positionQueue' - retrying using FixedBackOff{interval=5000, currentAttempts=2, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://fleetman-queue.default.svc.cluster.local:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
2020-05-30 13:03:18.333 ERROR 1 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'positionQueue' - retrying using FixedBackOff{interval=5000, currentAttempts=3, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://fleetman-queue.default.svc.cluster.local:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
2020-05-30 13:03:30.370 ERROR 1 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'positionQueue' - retrying using FixedBackOff{interval=5000, currentAttempts=4, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://fleetman-queue.default.svc.cluster.local:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
2020-05-30 13:03:36.379 ERROR 1 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'positionQueue' - retrying using FixedBackOff{interval=5000, currentAttempts=5, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://fleetman-queue.default.svc.cluster.local:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
2020-05-30 13:03:42.400 ERROR 1 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'positionQueue' - retrying using FixedBackOff{interval=5000, currentAttempts=6, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://fleetman-queue.default.svc.cluster.local:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
2020-05-30 13:03:48.415 ERROR 1 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'positionQueue' - retrying using FixedBackOff{interval=5000, currentAttempts=7, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://fleetman-queue.default.svc.cluster.local:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
2020-05-30 13:03:54.469 ERROR 1 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'positionQueue' - retrying using FixedBackOff{interval=5000, currentAttempts=8, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://fleetman-queue.default.svc.cluster.local:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
2020-05-30 13:04:06.492 ERROR 1 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'positionQueue' - retrying using FixedBackOff{interval=5000, currentAttempts=9, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://fleetman-queue.default.svc.cluster.local:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
2020-05-30 13:04:12.508 ERROR 1 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'positionQueue' - retrying using FixedBackOff{interval=5000, currentAttempts=10, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://fleetman-queue.default.svc.cluster.local:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
2020-05-30 13:04:18.528 ERROR 1 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'positionQueue' - retrying using FixedBackOff{interval=5000, currentAttempts=11, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://fleetman-queue.default.svc.cluster.local:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
2020-05-30 13:04:24.540 ERROR 1 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'positionQueue' - retrying using FixedBackOff{interval=5000, currentAttempts=12, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://fleetman-queue.default.svc.cluster.local:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
2020-05-30 13:04:30.556 ERROR 1 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'positionQueue' - retrying using FixedBackOff{interval=5000, currentAttempts=13, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://fleetman-queue.default.svc.cluster.local:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
2020-05-30 13:04:42.591 ERROR 1 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'positionQueue' - retrying using FixedBackOff{interval=5000, currentAttempts=14, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://fleetman-queue.default.svc.cluster.local:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
2020-05-30 13:04:48.604 ERROR 1 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'positionQueue' - retrying using FixedBackOff{interval=5000, currentAttempts=15, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://fleetman-queue.default.svc.cluster.local:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
2020-05-30 13:04:54.620 ERROR 1 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'positionQueue' - retrying using FixedBackOff{interval=5000, currentAttempts=16, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://fleetman-queue.default.svc.cluster.local:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
2020-05-30 13:05:00.636 ERROR 1 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'positionQueue' - retrying using FixedBackOff{interval=5000, currentAttempts=17, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://fleetman-queue.default.svc.cluster.local:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
2020-05-30 13:05:06.652 ERROR 1 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'positionQueue' - retrying using FixedBackOff{interval=5000, currentAttempts=18, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://fleetman-queue.default.svc.cluster.local:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
2020-05-30 13:05:18.688 ERROR 1 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'positionQueue' - retrying using FixedBackOff{interval=5000, currentAttempts=19, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://fleetman-queue.default.svc.cluster.local:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
2020-05-30 13:05:24.700 ERROR 1 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'positionQueue' - retrying using FixedBackOff{interval=5000, currentAttempts=20, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://fleetman-queue.default.svc.cluster.local:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
2020-05-30 13:05:29.702 ERROR 1 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'positionQueue' - retrying using FixedBackOff{interval=5000, currentAttempts=21, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://fleetman-queue.default.svc.cluster.local:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
2020-05-30 13:05:34.977  INFO 1 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Successfully refreshed JMS Connection
```

**Comment by DickChesterwood** [comment] 2020-05-31 13:36
Thanks for this. It's finding the queue successfully, so that's my theory ruined. 

I'm currently looking into a similar problem with the websockets failing to work, as it might be related I'll report back when I've finished with that problem. I hope this will be Monday sometime.

**Comment by traintes** [comment] 2020-08-06 07:02
May I ask for an update regarding this issue? It's been a while now and it essentially blocks me from continuing the course.

**Comment by DickChesterwood** [comment] 2020-08-06 09:43
I'll need to get tuned back into the problem - looking back it seems that the initial problem is fixed, and you're able to see the webapp, so we've got DNS working correctly now.

But, the vehicles are still not moving around? 

The log you've posted does show a lot of connection problems but it eventually connects, so I think all is actually well there.

First, can you post up the rest of your logs please? I suspect however that all the containers are working ok.

I suspect some obscure problem with the websockets. Can you pull up the javscript console for your browser and post up what you see in there? There will be a lot of logging but I'm interested in any connection errors.

Which browser are you using out of interest?

**Comment by traintes** [comment] 2020-08-10 19:29
I was just waiting for a response here and I didn't realize up until now that you've already updated the Docker image in the meantime. And I haven't verified the issue before posting the previous message. So, sorry about that. It's working now - thank you!

**Closed** 2021-11-18 18:57 UTC
